"""
Proposition data — all 48 Euclid Book I propositions + textbook theorems.

Each proposition includes metadata for the UI: name, statement, given objects,
required steps, conclusion, and applicability constraints.

Formal content (sequents, theorems) is linked to the System E
library via ``get_e_theorem()``, keeping display metadata here and
formal mathematics in the verifier.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class GivenObjects:
    points: List[dict] = field(default_factory=list)
    segments: List[dict] = field(default_factory=list)
    circles: List[dict] = field(default_factory=list)
    angle_marks: List[dict] = field(default_factory=list)


@dataclass
class Proposition:
    id: str
    source: str
    book: str
    name: str
    prop_number: Optional[int]
    max_proposition: int
    title: str
    statement: str
    given: str = ""
    diagram_hint: str = ""
    conclusion: str = ""
    conclusion_predicate: str = ""
    given_objects: Optional[GivenObjects] = None
    requires: List[dict] = field(default_factory=list)
    produces: str = ""
    required_steps: List[dict] = field(default_factory=list)
    difficulty: int = 1
    hints: List[str] = field(default_factory=list)
    notes: str = ""

    @property
    def e_library_name(self) -> Optional[str]:
        """Return the System E library key (e.g. ``Prop.I.1``), or None for non-Euclid entries."""
        if self.source == "euclid" and self.id.startswith("euclid-"):
            return "Prop." + self.id.replace("euclid-", "")
        return None

    def get_e_theorem(self):
        """Retrieve the ``ETheorem`` from the System E library.

        Returns ``None`` for non-Euclid entries or if the theorem is
        not (yet) in the library.
        """
        name = self.e_library_name
        if name is None:
            return None
        try:
            from verifier.e_library import E_THEOREM_LIBRARY
            return E_THEOREM_LIBRARY.get(name)
        except ImportError:
            return None

    @property
    def formal_sequent(self) -> Optional[str]:
        """Return the formal System E sequent as a string, or None."""
        thm = self.get_e_theorem()
        if thm is None:
            return None
        return str(thm.sequent)


def _go(pts=None, segs=None, circs=None, angles=None) -> GivenObjects:
    return GivenObjects(
        points=pts or [],
        segments=segs or [],
        circles=circs or [],
        angle_marks=angles or [],
    )


PROPOSITIONS: List[Proposition] = [
    Proposition("euclid-I.1", "euclid", "Book I", "Proposition I.1", 1, 0,
                 "Equilateral Triangle Construction",
                 "To construct an equilateral triangle on a given finite straight-line.",
                 given="A finite straight-line AB is given.",
                 conclusion="Triangle ABC is equilateral, constructed on the given line AB. Q.E.F.",
                 conclusion_predicate="ab = ac, ab = bc, ¬(c = a), ¬(c = b)",
                 given_objects=_go([{"label": "a", "x": 200, "y": 300}, {"label": "b", "x": 450, "y": 300}],
                                   [{"from": "a", "to": "b"}]),
                 requires=[{"type": "segment", "label": "Base segment"}],
                 difficulty=2,
                 hints=["Construct two circles, each centered at one endpoint passing through the other.",
                        "The intersection of the circles gives the third vertex.",
                        "Use Segment transfer to show all three sides are equal."]),
    Proposition("euclid-I.2", "euclid", "Book I", "Proposition I.2", 2, 1,
                 "Transfer a Length to a Point",
                 "To place at a given point a straight-line equal to a given straight-line.",
                 given="Point A and segment BC are given.",
                 conclusion="Segment AL equals BC. Q.E.F.",
                 conclusion_predicate="af = bc",
                 given_objects=_go([{"label": "a", "x": 200, "y": 250}, {"label": "b", "x": 350, "y": 350}, {"label": "c", "x": 480, "y": 350}],
                                   [{"from": "b", "to": "c"}]),
                 requires=[{"type": "point", "label": "Target point"}, {"type": "segment", "label": "Segment to transfer"}],
                 difficulty=3,
                 hints=["First construct an equilateral triangle on segment AB using Prop.I.1.",
                        "Extend sides of that triangle using circle constructions.",
                        "Use Segment transfer axioms to establish the equality."]),
    Proposition("euclid-I.3", "euclid", "Book I", "Proposition I.3", 3, 2,
                 "Cut Off Equal Length",
                 "Given two unequal straight-lines, cut off from the greater a straight-line equal to the less.",
                 given="Segments AB (greater) and C (lesser).",
                 conclusion="AE equals C. Q.E.F.",
                 conclusion_predicate="between(a, e, b), ae = cd",
                 given_objects=_go([{"label": "a", "x": 150, "y": 300},
                                    {"label": "b", "x": 500, "y": 300},
                                    {"label": "c", "x": 200, "y": 400},
                                    {"label": "d", "x": 350, "y": 400}],
                                   [{"from": "a", "to": "b"},
                                    {"from": "c", "to": "d"}]),
                 difficulty=2,
                 hints=["Use Prop.I.2 to transfer the shorter segment to an endpoint of the longer.",
                        "Construct a circle centered at A with radius equal to the shorter segment."]),
    Proposition("euclid-I.4", "euclid", "Book I", "Proposition I.4", 4, 3,
                 "SAS Congruence",
                 "If two triangles have two sides equal and the included angle equal, the triangles are congruent.",
                 given="Triangles ABC and DEF with AB=DE, AC=DF, ∠BAC=∠EDF.",
                 conclusion="The triangles are congruent. Q.E.D.",
                 conclusion_predicate="bc = ef, ∠abc = ∠def, ∠bca = ∠efd, △abc = △def",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 400, "y": 200},
                                    {"label": "e", "x": 350, "y": 380},
                                    {"label": "f", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=1,
                 hints=["This is directly the SAS superposition axiom."]),
    Proposition("euclid-I.5", "euclid", "Book I", "Proposition I.5", 5, 4,
                 "Isosceles Base Angles",
                 "In isosceles triangles the angles at the base are equal.",
                 given="Triangle ABC with AB = AC.",
                 conclusion="∠ABC = ∠ACB. Q.E.D.",
                 conclusion_predicate="∠abc = ∠acb",
                 given_objects=_go([{"label": "a", "x": 325, "y": 150},
                                    {"label": "b", "x": 175, "y": 400},
                                    {"label": "c", "x": 475, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=2,
                 hints=["Use M3 (segment symmetry) to get ba = ca, then apply SAS with the equal base angles."]),
    Proposition("euclid-I.6", "euclid", "Book I", "Proposition I.6", 6, 5,
                 "Converse of Isosceles Base Angles",
                 "If two angles of a triangle are equal, the sides subtending them are equal.",
                 given="Triangle ABC with ∠ABC = ∠ACB.",
                 conclusion="AB = AC. Q.E.D.",
                 conclusion_predicate="ab = ac",
                 given_objects=_go([{"label": "a", "x": 325, "y": 150},
                                    {"label": "b", "x": 175, "y": 400},
                                    {"label": "c", "x": 475, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=3,
                 hints=["Assume AB ≠ AC and derive a contradiction.",
                        "Use Prop.I.3 to cut off a segment equal to the shorter side, then apply Prop.I.5."]),
    Proposition("euclid-I.7", "euclid", "Book I", "Proposition I.7", 7, 6,
                 "Unique Triangle on Segment",
                 "Given a segment, there cannot be two distinct triangles on the same side with equal corresponding sides.",
                 given="Segment AB with triangles ABC and ABD on same side.",
                 conclusion="C and D coincide. Q.E.D.",
                 conclusion_predicate="c = d",
                 given_objects=_go([{"label": "a", "x": 175, "y": 380},
                                    {"label": "b", "x": 475, "y": 380},
                                    {"label": "c", "x": 300, "y": 180},
                                    {"label": "d", "x": 350, "y": 220}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "a", "to": "d"}, {"from": "b", "to": "d"}]),
                 difficulty=4,
                 hints=["Use Prop.I.5 to show base angles of the isosceles sub-triangles are equal.",
                        "Apply proof by contradiction: assume C ≠ D and derive contradictory angle inequalities."]),
    Proposition("euclid-I.8", "euclid", "Book I", "Proposition I.8", 8, 7,
                 "SSS Congruence",
                 "If two triangles have three sides pairwise equal, they are congruent.",
                 given="Triangles ABC and DEF with AB=DE, BC=EF, CA=FD.",
                 conclusion="The triangles are congruent. Q.E.D.",
                 conclusion_predicate="∠bac = ∠edf, ∠abc = ∠def, ∠bca = ∠efd, △abc = △def",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 400, "y": 200},
                                    {"label": "e", "x": 350, "y": 380},
                                    {"label": "f", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=1,
                 hints=["This is directly the SSS superposition axiom."]),
    Proposition("euclid-I.9", "euclid", "Book I", "Proposition I.9", 9, 8,
                 "Bisect an Angle",
                 "To bisect a given rectilineal angle.",
                 given="Angle BAC.",
                 conclusion="AD bisects angle BAC. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 350},
                                    {"label": "b", "x": 450, "y": 350},
                                    {"label": "c", "x": 350, "y": 150}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}],
                                   [],
                                   [{"from": "b", "vertex": "a", "to": "c"}]),
                 difficulty=4,
                 hints=["Use Prop.I.10 to bisect a segment, then apply SSS to prove the angle equality.",
                        "The proof depends on I.10 (not I.10 on I.9) to break the historical circular dependency."]),
    Proposition("euclid-I.10", "euclid", "Book I", "Proposition I.10", 10, 9,
                 "Bisect a Segment",
                 "To bisect a given finite straight-line.",
                 given="Segment AB.",
                 conclusion="D is the midpoint of AB. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 175, "y": 300},
                                    {"label": "b", "x": 475, "y": 300}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=5,
                 hints=["This is the hardest early proposition — uses the Gupta (1965) method.",
                        "Construct two equidistant points via circle-circle intersection, then draw a line through them.",
                        "Apply SSS and SAS to show the midpoint lies on the bisecting line."]),
    Proposition("euclid-I.11", "euclid", "Book I", "Proposition I.11", 11, 10,
                 "Perpendicular from Point on Line",
                 "To draw a perpendicular to a given line from a point on it.",
                 given="Line AB and point C on it.",
                 conclusion="CF is perpendicular to AB at C. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 300},
                                    {"label": "b", "x": 500, "y": 300}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=3,
                 hints=["Use Prop.I.3 to cut off equal segments on either side of the point.",
                        "Construct an equilateral triangle on that base, then use SAS."]),
    Proposition("euclid-I.12", "euclid", "Book I", "Proposition I.12", 12, 11,
                 "Perpendicular from Point off Line",
                 "To draw a perpendicular to a given line from a point not on it.",
                 given="Line AB and point C not on it.",
                 conclusion="CH is perpendicular to AB. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 350},
                                    {"label": "b", "x": 500, "y": 350},
                                    {"label": "p", "x": 325, "y": 150}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=3,
                 hints=["Draw a circle from the external point cutting the line in two places.",
                        "Use Prop.I.10 to bisect the chord, then SAS to establish the right angle."]),
    Proposition("euclid-I.13", "euclid", "Book I", "Proposition I.13", 13, 12,
                 "Supplementary Angles",
                 "If a straight line stands on another, the adjacent angles sum to two right angles.",
                 given="Line CD standing on AB at point B.",
                 conclusion="∠ABC + ∠ABD = 180°. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 350},
                                    {"label": "b", "x": 500, "y": 350},
                                    {"label": "c", "x": 325, "y": 350},
                                    {"label": "d", "x": 325, "y": 150}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}]),
                 difficulty=1,
                 hints=["This is directly Angle transfer 6 — supplementary angles from betweenness."]),
    Proposition("euclid-I.14", "euclid", "Book I", "Proposition I.14", 14, 13,
                 "Converse of Supplementary",
                 "If adjacent angles on one side sum to two right angles, the lines form a straight line.",
                 given="Angles on one side summing to 180°.",
                 conclusion="The lines are in a straight line. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 350},
                                    {"label": "b", "x": 325, "y": 350},
                                    {"label": "c", "x": 500, "y": 350},
                                    {"label": "d", "x": 325, "y": 150}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"}, {"from": "b", "to": "d"}]),
                 difficulty=1,
                 hints=["This is directly Angle transfer 7 — betweenness from supplementary angles."]),
    Proposition("euclid-I.15", "euclid", "Book I", "Proposition I.15", 15, 14,
                 "Vertical Angles",
                 "Vertical angles are equal.",
                 given="Two lines intersecting at E.",
                 conclusion="∠AEC = ∠DEB and ∠AED = ∠BEC. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 500, "y": 400},
                                    {"label": "c", "x": 500, "y": 200},
                                    {"label": "d", "x": 150, "y": 400},
                                    {"label": "e", "x": 325, "y": 300}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}]),
                 difficulty=2,
                 hints=["Apply Prop.I.13 twice to get two supplementary angle pairs.",
                        "Use CN3 (subtraction) to derive the equality of vertical angles."]),
    Proposition("euclid-I.16", "euclid", "Book I", "Proposition I.16", 16, 15,
                 "Exterior Angle Theorem",
                 "An exterior angle of a triangle is greater than either remote interior angle.",
                 given="Triangle ABC with BC extended to D.",
                 conclusion="∠ACD > ∠ABC and ∠ACD > ∠BAC. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 250, "y": 150},
                                    {"label": "b", "x": 150, "y": 350},
                                    {"label": "c", "x": 400, "y": 350},
                                    {"label": "d", "x": 550, "y": 350}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "c", "to": "d"}]),
                 difficulty=3,
                 hints=["Extend BC beyond C and bisect the extended segment.",
                        "Use SAS to show the exterior angle exceeds each remote interior angle."]),
    Proposition("euclid-I.17", "euclid", "Book I", "Proposition I.17", 17, 16,
                 "Two Angles Less Than Two Right Angles",
                 "Any two angles of a triangle are together less than two right angles.",
                 given="Triangle ABC.",
                 conclusion="∠ABC + ∠BCA < 180°. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 250, "y": 150},
                                    {"label": "b", "x": 150, "y": 380},
                                    {"label": "c", "x": 450, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=2,
                 hints=["This follows from Prop.I.16 applied to both remote interior angles."]),
    Proposition("euclid-I.18", "euclid", "Book I", "Proposition I.18", 18, 17,
                 "Greater Side Opposite Greater Angle",
                 "In any triangle, the greater side subtends the greater angle.",
                 given="Triangle ABC with AC > AB.",
                 conclusion="∠ABC > ∠BCA. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 150},
                                    {"label": "b", "x": 150, "y": 380},
                                    {"label": "c", "x": 500, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=3,
                 hints=["Place a point D on AC such that AD = AB, forming an isosceles triangle.",
                        "Use Prop.I.5 on the isosceles triangle, then Prop.I.16."]),
    Proposition("euclid-I.19", "euclid", "Book I", "Proposition I.19", 19, 18,
                 "Greater Angle Opposite Greater Side",
                 "In any triangle, the greater angle is subtended by the greater side.",
                 given="Triangle ABC with ∠ABC > ∠BCA.",
                 conclusion="AC > AB. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 150},
                                    {"label": "b", "x": 150, "y": 380},
                                    {"label": "c", "x": 500, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=3,
                 hints=["Prove by contradiction: assume the opposite and apply Prop.I.18."]),
    Proposition("euclid-I.20", "euclid", "Book I", "Proposition I.20", 20, 19,
                 "Triangle Inequality",
                 "In any triangle, the sum of any two sides is greater than the third.",
                 given="Triangle ABC.",
                 conclusion="BA + AC > BC. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 250, "y": 150},
                                    {"label": "b", "x": 150, "y": 380},
                                    {"label": "c", "x": 450, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=3,
                 hints=["Extend BA beyond A to a point D with AD = AC.",
                        "Apply Prop.I.5 to the isosceles triangle and use Prop.I.19."]),
    Proposition("euclid-I.21", "euclid", "Book I", "Proposition I.21", 21, 20,
                 "Interior Triangle Sides and Angles",
                 "If from the ends of a side of a triangle two lines are drawn to a point within the triangle, their sum is less than the remaining two sides, but the angle they contain is greater.",
                 given="Triangle ABC with point D inside.",
                 conclusion="BD + CD < BA + CA and ∠BDC > ∠BAC. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 300, "y": 120},
                                    {"label": "b", "x": 130, "y": 400},
                                    {"label": "c", "x": 470, "y": 400},
                                    {"label": "d", "x": 300, "y": 310}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "b", "to": "d"}, {"from": "c", "to": "d"}]),
                 difficulty=4,
                 hints=["Extend BD to meet AC and use the triangle inequality on sub-triangles.",
                        "Apply Prop.I.16 and Prop.I.20 to the sub-triangles formed."]),
    Proposition("euclid-I.22", "euclid", "Book I", "Proposition I.22", 22, 21,
                 "Triangle from Three Segments",
                 "To construct a triangle from three given line segments (subject to the triangle inequality).",
                 given="Three segments.",
                 conclusion="Triangle KFG constructed. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 100, "y": 200},
                                    {"label": "b", "x": 250, "y": 200},
                                    {"label": "c", "x": 100, "y": 280},
                                    {"label": "d", "x": 300, "y": 280},
                                    {"label": "e", "x": 100, "y": 360},
                                    {"label": "f", "x": 280, "y": 360}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}, {"from": "e", "to": "f"}]),
                 difficulty=3,
                 hints=["Transfer each segment to a common point using Prop.I.2 and Prop.I.3.",
                        "Use two circle constructions to find the third vertex."]),
    Proposition("euclid-I.23", "euclid", "Book I", "Proposition I.23", 23, 22,
                 "Copy an Angle",
                 "To construct an angle equal to a given angle on a given line at a given point.",
                 given="Angle DCE and line AB with point A.",
                 conclusion="∠FAG = ∠DCE. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 350},
                                    {"label": "b", "x": 450, "y": 350},
                                    {"label": "d", "x": 350, "y": 100},
                                    {"label": "e", "x": 500, "y": 200},
                                    {"label": "f", "x": 550, "y": 100}],
                                   [{"from": "a", "to": "b"}, {"from": "d", "to": "e"}, {"from": "e", "to": "f"}],
                                   [],
                                   [{"from": "d", "vertex": "e", "to": "f"}]),
                 difficulty=3,
                 hints=["Construct a triangle with sides equal to the sides of the given angle using Prop.I.22.",
                        "Apply SSS to establish the angle equality."]),
    Proposition("euclid-I.24", "euclid", "Book I", "Proposition I.24", 24, 23,
                 "Hinge Theorem",
                 "If two sides of one triangle equal two sides of another but the included angle is greater, the base is greater.",
                 given="Triangles with equal pairs of sides.",
                 conclusion="The base opposite the greater angle is greater. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 180},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 400, "y": 180},
                                    {"label": "e", "x": 350, "y": 380},
                                    {"label": "f", "x": 580, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=4,
                 hints=["Place the angle DEG equal to BAC on segment DE using Prop.I.23.",
                        "Show DG = DF by construction, then use Prop.I.4 (SAS)."]),
    Proposition("euclid-I.25", "euclid", "Book I", "Proposition I.25", 25, 24,
                 "Converse Hinge Theorem",
                 "If two sides equal two sides and the base is greater, the angle is greater.",
                 given="Triangles with equal pairs of sides.",
                 conclusion="The angle opposite the greater base is greater. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 180},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 400, "y": 180},
                                    {"label": "e", "x": 350, "y": 380},
                                    {"label": "f", "x": 580, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=3,
                 hints=["Prove by contradiction using Prop.I.24 (the forward direction)."]),
    Proposition("euclid-I.26", "euclid", "Book I", "Proposition I.26", 26, 25,
                 "ASA and AAS Congruence",
                 "Triangles with two angles and a corresponding side equal are congruent.",
                 given="Triangles with matching angle-side combinations.",
                 conclusion="The triangles are congruent. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 400, "y": 200},
                                    {"label": "e", "x": 350, "y": 380},
                                    {"label": "f", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=4,
                 hints=["Two cases: ASA and AAS. Both use proof by contradiction.",
                        "For ASA: assume a side is not equal, cut off an equal part, apply SAS, get contradictory angles.",
                        "For AAS: use Prop.I.4 after deriving the third angle."]),
    Proposition("euclid-I.27", "euclid", "Book I", "Proposition I.27", 27, 26,
                 "Alternate Interior Angles Imply Parallel",
                 "If a transversal makes alternate interior angles equal, the lines are parallel.",
                 given="Lines AB, CD cut by transversal EF with ∠AEF = ∠EFD.",
                 conclusion="AB ∥ CD. Q.E.D.",
                 conclusion_predicate="¬intersects(L, M)",
                 given_objects=_go([{"label": "a", "x": 100, "y": 200},
                                    {"label": "b", "x": 550, "y": 200},
                                    {"label": "c", "x": 100, "y": 380},
                                    {"label": "d", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}]),
                 difficulty=3,
                 hints=["Assume the lines meet and derive a contradiction using Prop.I.16."]),
    Proposition("euclid-I.28", "euclid", "Book I", "Proposition I.28", 28, 27,
                 "Exterior Angle Equals Opposite Interior Implies Parallel",
                 "If exterior angle equals opposite interior, the lines are parallel.",
                 given="Transversal making exterior = remote interior.",
                 conclusion="The lines are parallel. Q.E.D.",
                 conclusion_predicate="¬intersects(L, M)",
                 given_objects=_go([{"label": "a", "x": 100, "y": 200},
                                    {"label": "b", "x": 550, "y": 200},
                                    {"label": "c", "x": 100, "y": 380},
                                    {"label": "d", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}]),
                 difficulty=3,
                 hints=["Reduce to Prop.I.27 using Prop.I.13 (supplementary angles) or Prop.I.15 (vertical angles)."]),
    Proposition("euclid-I.29", "euclid", "Book I", "Proposition I.29", 29, 28,
                 "Parallel Lines Give Equal Alternate Angles",
                 "A transversal cutting parallel lines makes alternate interior angles equal.",
                 given="Parallel lines AB ∥ CD cut by transversal.",
                 conclusion="Alternate interior angles are equal. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 100, "y": 200},
                                    {"label": "b", "x": 550, "y": 200},
                                    {"label": "c", "x": 100, "y": 380},
                                    {"label": "d", "x": 550, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}]),
                 difficulty=4,
                 hints=["This is the converse — uses the parallel postulate (Angle transfer 5a/5b).",
                        "Assume alternate angles are unequal and derive a contradiction using the parallel postulate."]),
    Proposition("euclid-I.30", "euclid", "Book I", "Proposition I.30", 30, 29,
                 "Lines Parallel to the Same Line",
                 "Lines parallel to the same line are parallel to each other.",
                 given="AB ∥ EF and CD ∥ EF.",
                 conclusion="AB ∥ CD. Q.E.D.",
                 conclusion_predicate="¬intersects(L, M)",
                 given_objects=_go([{"label": "a", "x": 100, "y": 160},
                                    {"label": "b", "x": 550, "y": 160},
                                    {"label": "c", "x": 100, "y": 290},
                                    {"label": "d", "x": 550, "y": 290},
                                    {"label": "e", "x": 100, "y": 420},
                                    {"label": "f", "x": 550, "y": 420}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"}, {"from": "e", "to": "f"}]),
                 difficulty=2,
                 hints=["Apply Prop.I.29 twice and use CN1 (transitivity of equality)."]),
    Proposition("euclid-I.31", "euclid", "Book I", "Proposition I.31", 31, 30,
                 "Construct Parallel Through a Point",
                 "Through a given point, draw a line parallel to a given line.",
                 given="Point A and line BC.",
                 conclusion="EAF ∥ BC. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 325, "y": 180},
                                    {"label": "b", "x": 150, "y": 350},
                                    {"label": "c", "x": 500, "y": 350}],
                                   [{"from": "b", "to": "c"}]),
                 difficulty=2,
                 hints=["Use Prop.I.23 to copy an angle and Prop.I.27 to establish parallelism."]),
    Proposition("euclid-I.32", "euclid", "Book I", "Proposition I.32", 32, 31,
                 "Exterior Angle = Sum of Remote Interior Angles",
                 "An exterior angle of a triangle equals the sum of the two non-adjacent interior angles; and the three interior angles sum to two right angles.",
                 given="Triangle ABC with BC extended to D.",
                 conclusion="∠ACD = ∠CAB + ∠ABC, and ∠A + ∠B + ∠C = 180°. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 250, "y": 150},
                                    {"label": "b", "x": 150, "y": 350},
                                    {"label": "c", "x": 400, "y": 350},
                                    {"label": "d", "x": 550, "y": 350}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "c", "to": "d"}]),
                 difficulty=3,
                 hints=["Draw a parallel through C using Prop.I.31.",
                        "Apply Prop.I.29 to get alternate angles, then use Prop.I.13."]),
    Proposition("euclid-I.33", "euclid", "Book I", "Proposition I.33", 33, 32,
                 "Joining Equal Parallels",
                 "Lines joining equal and parallel segments on the same side are themselves equal and parallel.",
                 given="AB = CD and AB ∥ CD.",
                 conclusion="AC = BD and AC ∥ BD. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 400, "y": 200},
                                    {"label": "c", "x": 200, "y": 400},
                                    {"label": "d", "x": 450, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "c", "to": "d"},
                                    {"from": "a", "to": "c"}, {"from": "b", "to": "d"}]),
                 difficulty=2,
                 hints=["Draw diagonal AC, apply Prop.I.29 for alternate angles, then SAS."]),
    Proposition("euclid-I.34", "euclid", "Book I", "Proposition I.34", 34, 33,
                 "Parallelogram Properties",
                 "In a parallelogram opposite sides and angles are equal, and the diagonal bisects the area.",
                 given="Parallelogram ABCD.",
                 conclusion="AB = CD, BC = AD, ∠A = ∠C, ∠B = ∠D. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 400, "y": 200},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 200, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"},
                                    {"from": "c", "to": "d"}, {"from": "d", "to": "a"}]),
                 difficulty=3,
                 hints=["Draw diagonal BC, apply Prop.I.29 for alternate angles, then use ASA."]),
    Proposition("euclid-I.35", "euclid", "Book I", "Proposition I.35", 35, 34,
                 "Parallelograms on Same Base Between Parallels",
                 "Parallelograms on the same base and between the same parallels have equal area.",
                 given="Parallelograms ABCD, EBCF on base BC between parallels.",
                 conclusion="Area(ABCD) = Area(EBCF). Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 200, "y": 400},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 400, "y": 200},
                                    {"label": "e", "x": 250, "y": 200},
                                    {"label": "f", "x": 500, "y": 200}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"}, {"from": "c", "to": "d"}, {"from": "d", "to": "a"},
                                    {"from": "e", "to": "b"}, {"from": "c", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=4,
                 hints=["Consider the several cases for the relative positions of D and E.",
                        "Use area addition/subtraction with Prop.I.34 and congruent triangles."]),
    Proposition("euclid-I.36", "euclid", "Book I", "Proposition I.36", 36, 35,
                 "Parallelograms on Equal Bases",
                 "Parallelograms on equal bases and between the same parallels have equal area.",
                 given="Parallelograms on equal bases between parallels.",
                 conclusion="They have equal area. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 120, "y": 200},
                                    {"label": "b", "x": 170, "y": 400},
                                    {"label": "c", "x": 320, "y": 400},
                                    {"label": "d", "x": 270, "y": 200},
                                    {"label": "e", "x": 370, "y": 200},
                                    {"label": "f", "x": 520, "y": 200}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"}, {"from": "c", "to": "d"}, {"from": "d", "to": "a"},
                                    {"from": "e", "to": "f"}]),
                 difficulty=3,
                 hints=["Connect the parallelograms via Prop.I.33 and Prop.I.34, then apply Prop.I.35."]),
    Proposition("euclid-I.37", "euclid", "Book I", "Proposition I.37", 37, 36,
                 "Triangles on Same Base Between Parallels",
                 "Triangles on the same base and between the same parallels have equal area.",
                 given="Triangles ABC, DBC on base BC between parallels.",
                 conclusion="Area(ABC) = Area(DBC). Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 200},
                                    {"label": "b", "x": 150, "y": 400},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 400, "y": 200}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "b"}, {"from": "d", "to": "c"}]),
                 difficulty=2,
                 hints=["Complete each triangle to a parallelogram and apply Prop.I.35.",
                        "Each triangle is half its corresponding parallelogram (Prop.I.34)."]),
    Proposition("euclid-I.38", "euclid", "Book I", "Proposition I.38", 38, 37,
                 "Triangles on Equal Bases Between Parallels",
                 "Triangles on equal bases and between the same parallels have equal area.",
                 given="Triangles on equal bases between parallels.",
                 conclusion="They have equal area. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 170, "y": 200},
                                    {"label": "b", "x": 120, "y": 400},
                                    {"label": "c", "x": 270, "y": 400},
                                    {"label": "d", "x": 430, "y": 200},
                                    {"label": "e", "x": 380, "y": 400},
                                    {"label": "f", "x": 530, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=2,
                 hints=["Same approach as Prop.I.37 but with equal bases instead of the same base."]),
    Proposition("euclid-I.39", "euclid", "Book I", "Proposition I.39", 39, 38,
                 "Equal Triangles on Same Base Are Between Parallels",
                 "Equal triangles on the same base and same side are between the same parallels.",
                 given="Equal-area triangles on the same base.",
                 conclusion="AD ∥ BC. Q.E.D.",
                 conclusion_predicate="¬intersects(L, M)",
                 given_objects=_go([{"label": "a", "x": 200, "y": 200},
                                    {"label": "b", "x": 150, "y": 400},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 400, "y": 200}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "b"}, {"from": "d", "to": "c"}]),
                 difficulty=3,
                 hints=["Prove by contradiction: assume not parallel, construct the parallel through A.",
                        "The triangle on the new parallel has the same area (I.37), contradicting uniqueness."]),
    Proposition("euclid-I.40", "euclid", "Book I", "Proposition I.40", 40, 39,
                 "Equal Triangles on Equal Bases Are Between Parallels",
                 "Equal triangles on equal bases and same side are between the same parallels.",
                 given="Equal-area triangles on equal bases.",
                 conclusion="AD ∥ BC. Q.E.D.",
                 conclusion_predicate="¬intersects(L, M)",
                 given_objects=_go([{"label": "a", "x": 170, "y": 200},
                                    {"label": "b", "x": 120, "y": 400},
                                    {"label": "c", "x": 270, "y": 400},
                                    {"label": "d", "x": 430, "y": 200},
                                    {"label": "e", "x": 380, "y": 400},
                                    {"label": "f", "x": 530, "y": 400}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}, {"from": "e", "to": "f"}]),
                 difficulty=3,
                 hints=["Same as Prop.I.39 but with equal bases."]),
    Proposition("euclid-I.41", "euclid", "Book I", "Proposition I.41", 41, 40,
                 "Parallelogram Double Triangle",
                 "A parallelogram has twice the area of a triangle on the same base and between the same parallels.",
                 given="Parallelogram ABCD and triangle EBC on base BC between parallels.",
                 conclusion="Area(ABCD) = 2·Area(EBC). Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 200},
                                    {"label": "b", "x": 200, "y": 400},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 400, "y": 200},
                                    {"label": "e", "x": 300, "y": 200}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"}, {"from": "c", "to": "d"}, {"from": "d", "to": "a"},
                                    {"from": "e", "to": "b"}, {"from": "e", "to": "c"}]),
                 difficulty=2,
                 hints=["The triangle is half the parallelogram by Prop.I.34 — apply Prop.I.35 or I.37."]),
    Proposition("euclid-I.42", "euclid", "Book I", "Proposition I.42", 42, 41,
                 "Construct Parallelogram Equal to Triangle",
                 "To construct a parallelogram equal in area to a given triangle in a given angle.",
                 given="Triangle ABC and angle D.",
                 conclusion="Parallelogram FECG equals triangle ABC. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 150},
                                    {"label": "b", "x": 100, "y": 350},
                                    {"label": "c", "x": 350, "y": 350},
                                    {"label": "d", "x": 450, "y": 250},
                                    {"label": "e", "x": 500, "y": 350},
                                    {"label": "f", "x": 550, "y": 250}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"},
                                    {"from": "d", "to": "e"}, {"from": "d", "to": "f"}],
                                   [],
                                   [{"from": "e", "vertex": "d", "to": "f"}]),
                 difficulty=3,
                 hints=["Bisect BC at E, construct the angle at E using Prop.I.23, then apply Prop.I.41."]),
    Proposition("euclid-I.43", "euclid", "Book I", "Proposition I.43", 43, 42,
                 "Complements of Parallelogram",
                 "In any parallelogram, the complements of the parallelograms about the diagonal are equal.",
                 given="Parallelogram ABCD with diagonal AC.",
                 conclusion="Complement BK = complement KD. Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 180},
                                    {"label": "b", "x": 400, "y": 180},
                                    {"label": "c", "x": 450, "y": 400},
                                    {"label": "d", "x": 200, "y": 400},
                                    {"label": "k", "x": 300, "y": 290}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"},
                                    {"from": "c", "to": "d"}, {"from": "d", "to": "a"},
                                    {"from": "a", "to": "c"}]),
                 difficulty=3,
                 hints=["Use Prop.I.34 on the full parallelogram and each sub-parallelogram.",
                        "Apply area subtraction to show the complements are equal."]),
    Proposition("euclid-I.44", "euclid", "Book I", "Proposition I.44", 44, 43,
                 "Apply Parallelogram to Line Segment",
                 "To apply a parallelogram equal to a given triangle to a given line in a given angle.",
                 given="Line AB, triangle C, angle D.",
                 conclusion="Parallelogram applied. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 150, "y": 300},
                                    {"label": "b", "x": 350, "y": 300},
                                    {"label": "c", "x": 200, "y": 150},
                                    {"label": "d", "x": 450, "y": 200},
                                    {"label": "e", "x": 500, "y": 300}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=5,
                 hints=["This is one of the hardest constructions in Book I.",
                        "Use Prop.I.42 to build a parallelogram equal to the triangle, then apply Prop.I.43."]),
    Proposition("euclid-I.45", "euclid", "Book I", "Proposition I.45", 45, 44,
                 "Construct Parallelogram Equal to Rectilineal Figure",
                 "To construct a parallelogram equal in area to a given rectilineal figure in a given angle.",
                 given="Rectilineal figure ABCD and angle E.",
                 conclusion="Parallelogram constructed. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 120, "y": 200},
                                    {"label": "b", "x": 100, "y": 380},
                                    {"label": "c", "x": 300, "y": 380},
                                    {"label": "d", "x": 280, "y": 200},
                                    {"label": "e", "x": 400, "y": 280},
                                    {"label": "f", "x": 460, "y": 380},
                                    {"label": "g", "x": 500, "y": 280}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"},
                                    {"from": "c", "to": "d"}, {"from": "d", "to": "a"},
                                    {"from": "e", "to": "f"}, {"from": "e", "to": "g"}],
                                   [],
                                   [{"from": "f", "vertex": "e", "to": "g"}]),
                 difficulty=4,
                 hints=["Divide the rectilineal figure into triangles.",
                        "Apply Prop.I.42 and Prop.I.44 iteratively to build up the parallelogram."]),
    Proposition("euclid-I.46", "euclid", "Book I", "Proposition I.46", 46, 45,
                 "Construct a Square",
                 "To construct a square on a given straight-line.",
                 given="Segment AB.",
                 conclusion="Square ABDC constructed. Q.E.F.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 400},
                                    {"label": "b", "x": 450, "y": 400}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=3,
                 hints=["Construct a perpendicular at A using Prop.I.11.",
                        "Cut off the right length using Prop.I.3, then use Prop.I.34 to verify."]),
    Proposition("euclid-I.47", "euclid", "Book I", "Proposition I.47", 47, 46,
                 "Pythagorean Theorem",
                 "In right-angled triangles, the square on the hypotenuse equals the sum of the squares on the other two sides.",
                 given="Right triangle ABC with right angle at A.",
                 conclusion="BC² = AB² + AC². Q.E.D.",
                 given_objects=_go([{"label": "a", "x": 200, "y": 380},
                                    {"label": "b", "x": 200, "y": 180},
                                    {"label": "c", "x": 450, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}],
                                   [],
                                   [{"from": "b", "vertex": "a", "to": "c", "is_right": True}]),
                 difficulty=5,
                 hints=["Construct squares on each side of the triangle.",
                        "Draw a perpendicular from the right angle vertex to the hypotenuse.",
                        "Use Prop.I.41 (parallelogram = 2×triangle) and Prop.I.14 (supplementary → collinear)."]),
    Proposition("euclid-I.48", "euclid", "Book I", "Proposition I.48", 48, 47,
                 "Converse of Pythagorean Theorem",
                 "If the square on one side equals the sum of squares on the other two, the angle opposite the first side is right.",
                 given="Triangle ABC with BC² = AB² + AC².",
                 conclusion="∠BAC is a right angle. Q.E.D.",
                 conclusion_predicate="∠bac = ∟",
                 given_objects=_go([{"label": "a", "x": 200, "y": 380},
                                    {"label": "b", "x": 200, "y": 180},
                                    {"label": "c", "x": 450, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "a", "to": "c"}, {"from": "b", "to": "c"}]),
                 difficulty=4,
                 hints=["Construct a right triangle with the same two shorter sides using Props.I.11 and I.3.",
                        "Apply Prop.I.47 to the constructed triangle, then use SSS."]),
]

TEXTBOOK_THEOREMS: List[Proposition] = [
    Proposition("tb-thm-2.1", "textbook", "Ch. 2", "Theorem 2.1", None, 48,
                 "Unique Midpoint",
                 "Every line segment has exactly one midpoint: a point M on AB such that AM = MB.",
                 given="A line segment AB with A ≠ B.",
                 conclusion="There exists a unique point M such that between(A, M, B) and AM = MB. Q.E.D.",
                 conclusion_predicate="between(a,m,b), am = mb",
                 given_objects=_go([{"label": "a", "x": 150, "y": 300},
                                    {"label": "b", "x": 500, "y": 300},
                                    {"label": "m", "x": 325, "y": 300}],
                                   [{"from": "a", "to": "b"}]),
                 difficulty=2,
                 hints=["Apply Prop.I.10 for existence, then use proof by contradiction for uniqueness."]),
    Proposition("tb-thm-4.1", "textbook", "Ch. 4", "Theorem 4.1", None, 48,
                 "Triangle Angle Sum",
                 "The three interior angles of any triangle sum to two right angles (180°).",
                 given="Triangle ABC.",
                 conclusion="∠BAC + ∠ABC + ∠BCA = two right angles. Q.E.D.",
                 conclusion_predicate="∠bac + ∠abc + ∠bca = ∟ + ∟",
                 given_objects=_go([{"label": "a", "x": 325, "y": 150},
                                    {"label": "b", "x": 150, "y": 380},
                                    {"label": "c", "x": 500, "y": 380}],
                                   [{"from": "a", "to": "b"}, {"from": "b", "to": "c"}, {"from": "a", "to": "c"}]),
                 difficulty=3,
                 hints=["This is essentially Prop.I.32. Draw a parallel through one vertex and use alternate angles."]),
]

ALL_PROPOSITIONS: List[Proposition] = PROPOSITIONS + TEXTBOOK_THEOREMS


def get_proposition(prop_id: str) -> Optional[Proposition]:
    return next((p for p in ALL_PROPOSITIONS if p.id == prop_id), None)


def get_allowed_propositions(max_prop: int) -> List[Proposition]:
    return [p for p in PROPOSITIONS if p.prop_number is not None and p.prop_number <= max_prop]


# ═══════════════════════════════════════════════════════════════════════
# Formal system linkage helpers (Phase 6.5.3)
# ═══════════════════════════════════════════════════════════════════════

def get_e_sequent(prop_id: str) -> Optional[str]:
    """Return the formal System E sequent string for a proposition.

    Args:
        prop_id: e.g. ``"euclid-I.1"``

    Returns:
        The sequent string (e.g. ``"¬(a = b) ⇒ ∃c:POINT. ab = ac, …"``),
        or ``None`` if the proposition has no E library entry.
    """
    prop = get_proposition(prop_id)
    if prop is None:
        return None
    return prop.formal_sequent


def get_all_formal_links() -> Dict[str, dict]:
    """Return a mapping from proposition id to its formal-system links.

    Each value is a dict with keys ``e_name`` and ``e_sequent``.
    """
    result: Dict[str, dict] = {}
    for prop in PROPOSITIONS:
        e_thm = prop.get_e_theorem()
        result[prop.id] = {
            "e_name": prop.e_library_name,
            "e_sequent": str(e_thm.sequent) if e_thm else None,
        }
    return result
